#ifndef __COMMON_TYPEDEFS_H__
#define __COMMON_TYPEDEFS_H__

#include <stddef.h>

struct BackupBlock;
typedef struct BackupBlock BackupBlock;
struct BigFastBitmap;
typedef struct BigFastBitmap BigFastBitmap;
struct Bitmap;
typedef struct Bitmap Bitmap;
struct BitString;
typedef struct BitString BitString;
struct CallDescriptor;
typedef struct CallDescriptor CallDescriptor;
struct ChildrenCollection;
typedef struct ChildrenCollection ChildrenCollection;
struct cpu;
typedef struct cpu cpu;
struct cpu_user_regs_disas;
typedef struct cpu_user_regs_disas cpu_user_regs_disas;
struct cred;
typedef struct cred cred;
struct DirectoryEntry;
typedef struct DirectoryEntry DirectoryEntry;
struct dlist;
typedef struct dlist dlist;
struct dlist_head;
typedef struct dlist_head dlist_head;
struct dlist_head_list;
typedef struct dlist_head_list dlist_head_list;
struct DR;
typedef struct DR DR;
struct DR6;
typedef struct DR6 DR6;
struct DR7;
typedef struct DR7 DR7;
struct EncBlocks;
typedef struct EncBlocks EncBlocks;
struct ExternalLabel;
typedef struct ExternalLabel ExternalLabel;
struct FastBitmap;
typedef struct FastBitmap FastBitmap;
struct FB;
typedef struct FB FB;
struct FB_Bitfield;
typedef struct FB_Bitfield FB_Bitfield;
struct FB_Info;
typedef struct FB_Info FB_Info;
struct ForkedInfo;
typedef struct ForkedInfo ForkedInfo;
struct form;
typedef struct form form;
struct form_parse_data;
typedef struct form_parse_data form_parse_data;
//struct FS;
//typedef struct FS FS; XXX FS is also a symbol in nexus-gdb.c
struct FS_iovec;
typedef struct FS_iovec FS_iovec;
struct FS_NodeID;
typedef struct FS_NodeID FS_NodeID;
struct FS_NodeID_and_Rcode;
typedef struct FS_NodeID_and_Rcode FS_NodeID_and_Rcode;
struct GDT;
typedef struct GDT GDT;
struct GDT_Descriptor;
typedef struct GDT_Descriptor GDT_Descriptor;
struct GenericList;
typedef struct GenericList GenericList;
struct GenericNode;
typedef struct GenericNode GenericNode;
struct GenericSet;
typedef struct GenericSet GenericSet;
struct Grounds;
typedef struct Grounds Grounds;
struct _Grounds;
typedef struct _Grounds _Grounds;
struct guard;
typedef struct guard guard;
struct HandleTable;
typedef struct HandleTable HandleTable;
struct HashTable;
typedef struct HashTable HashTable;
struct Hashtree;
typedef struct Hashtree Hashtree;
struct IDTEntryHi;
typedef struct IDTEntryHi IDTEntryHi;
struct IDTEntryLo;
typedef struct IDTEntryLo IDTEntryLo;
struct IEvent;
typedef struct IEvent IEvent;
struct IEvent_Call_Info;
typedef struct IEvent_Call_Info IEvent_Call_Info;
struct IEvent_Info;
typedef struct IEvent_Info IEvent_Info;
struct IEvent_Syscall_Info;
typedef struct IEvent_Syscall_Info IEvent_Syscall_Info;
struct IEvent_Transfer_Info;
typedef struct IEvent_Transfer_Info IEvent_Transfer_Info;
// struct in;
// typedef struct in in;
struct InterfaceNode;
typedef struct InterfaceNode InterfaceNode;
struct InterruptState;
typedef struct InterruptState InterruptState;
struct IPC;
typedef struct IPC IPC;
struct IPC_EdgeDescription;
typedef struct IPC_EdgeDescription IPC_EdgeDescription;
struct IPC_Port;
typedef struct IPC_Port IPC_Port;
struct IPD;
typedef struct IPD IPD;
struct IretFrame;
typedef struct IretFrame IretFrame;
struct is;
typedef struct is is;
struct Keys;
typedef struct Keys Keys;
struct KShMem;
typedef struct KShMem KShMem;
struct KShSegment;
typedef struct KShSegment KShSegment;
struct KVKey_tpm;
typedef struct KVKey_tpm KVKey_tpm;
struct KVKey_nrk;
typedef struct KVKey_nrk KVKey_nrk;
struct KVKey_nsk;
typedef struct KVKey_nsk KVKey_nsk;
struct KVKey_public;
typedef struct KVKey_public KVKey_public;
struct Label;
typedef struct Label Label;
struct LabelInformation;
typedef struct LabelInformation LabelInformation;
struct Map;
typedef struct Map Map;
struct MouseEvent;
typedef struct MouseEvent MouseEvent;
struct MReadCont;
typedef struct MReadCont MReadCont;
struct MReadCont_and_Rcode;
typedef struct MReadCont_and_Rcode MReadCont_and_Rcode;
struct MReadDesc;
typedef struct MReadDesc MReadDesc;
struct MTRR;
typedef struct MTRR MTRR;
struct MTRR_Base;
typedef struct MTRR_Base MTRR_Base;
struct MTRR_Mask;
typedef struct MTRR_Mask MTRR_Mask;
struct Name;
typedef struct Name Name;
struct NexusCall;
typedef struct NexusCall NexusCall;
struct NexusCall3Args;
typedef struct NexusCall3Args NexusCall3Args;
struct NexusCallArgs;
typedef struct NexusCallArgs NexusCallArgs;
struct NexusMachineState;
typedef struct NexusMachineState NexusMachineState;
struct NexusTrapInfo;
typedef struct NexusTrapInfo NexusTrapInfo;
struct NIOC;
typedef struct NIOC NIOC;
struct NIOC_Args;
typedef struct NIOC_Args NIOC_Args;
struct Node;
typedef struct Node Node;
struct NodeId;
typedef struct NodeId NodeId;
struct NodeID;
typedef struct NodeID NodeID;
struct NodeID_and_Rcode;
typedef struct NodeID_and_Rcode NodeID_and_Rcode;
struct NS;
typedef struct NS NS;
struct NS_SimpleRegisterCtx;
typedef struct NS_SimpleRegisterCtx NS_SimpleRegisterCtx;
struct OpCap;
typedef struct OpCap OpCap;
struct OpCapNode;
typedef struct OpCapNode OpCapNode;
struct opencred;
typedef struct opencred opencred;
struct PageTableEntry;
typedef struct PageTableEntry PageTableEntry;
struct ParsedX;
typedef struct ParsedX ParsedX;
struct ParsedX5;
typedef struct ParsedX5 ParsedX5;
struct ParsedX509;
typedef struct ParsedX509 ParsedX509;
struct PathNode;
typedef struct PathNode PathNode;
//struct PointerVector;
//typedef struct PointerVector PointerVector;
struct Policy;
typedef struct Policy Policy;
struct _Policy;
typedef struct _Policy _Policy;
struct PortQueueLengthInfo;
typedef struct PortQueueLengthInfo PortQueueLengthInfo;
struct PropertyNode;
typedef struct PropertyNode PropertyNode;
struct PubKey;
typedef struct PubKey PubKey;
struct QItem;
typedef struct QItem QItem;
struct QualifiedLabel;
typedef struct QualifiedLabel QualifiedLabel;
struct Queue;
typedef struct Queue Queue;
struct Remapargs;
typedef struct Remapargs Remapargs;
struct ResourceNode;
typedef struct ResourceNode ResourceNode;
struct SegmentDescriptor;
typedef struct SegmentDescriptor SegmentDescriptor;
struct SegmentDescriptorHi;
typedef struct SegmentDescriptorHi SegmentDescriptorHi;
struct SegmentDescriptorLo;
typedef struct SegmentDescriptorLo SegmentDescriptorLo;
struct Selector;
typedef struct Selector Selector;
struct SerialNum;
typedef struct SerialNum SerialNum;
struct sk;
typedef struct sk sk;
struct sk_buff;
typedef struct sk_buff sk_buff;
struct StringBuffer;
typedef struct StringBuffer StringBuffer;
struct TapInterferenceSpec;
typedef struct TapInterferenceSpec TapInterferenceSpec;
struct TapNotificationSpec;
typedef struct TapNotificationSpec TapNotificationSpec;
struct TapOrderSpec;
typedef struct TapOrderSpec TapOrderSpec;
struct TapOrderSpecEntry;
typedef struct TapOrderSpecEntry TapOrderSpecEntry;
struct TBSCertificate;
typedef struct TBSCertificate TBSCertificate;
struct term;
typedef struct term term;
struct term_auth;
typedef struct term_auth term_auth;
struct Timing;
typedef struct Timing Timing;
struct TimingSpec;
typedef struct TimingSpec TimingSpec;
struct TransferContext;
typedef struct TransferContext TransferContext;
struct TransferDesc;
typedef struct TransferDesc TransferDesc;
struct TSS;
typedef struct TSS TSS;
struct UQueue;
typedef struct UQueue UQueue;
struct UserNetdev;
typedef struct UserNetdev UserNetdev;
struct Validity;
typedef struct Validity Validity;
struct VarLen;
typedef struct VarLen VarLen;
struct VDIRargs;
typedef struct VDIRargs VDIRargs;
struct VDIRcargs;
typedef struct VDIRcargs VDIRcargs;
struct Vkeyargs;
typedef struct Vkeyargs Vkeyargs;
struct VKeyOp;
typedef struct VKeyOp VKeyOp;
struct x;
typedef struct x x;
struct X;
typedef struct X X;
struct x86_emulate_ctxt;
typedef struct x86_emulate_ctxt x86_emulate_ctxt;
struct x86_emulate_ops;
typedef struct x86_emulate_ops x86_emulate_ops;
struct X86_ErrorCode;
typedef struct X86_ErrorCode X86_ErrorCode;

#endif
