#ifndef __TYPEDEFS_H__
#define __TYPEDEFS_H__

#include <nexus/commontypedefs.h>

struct BasicThread;
typedef struct BasicThread BasicThread;
typedef struct BasicThread KThread;
typedef struct BasicThread UThread;

struct above;
typedef struct above above;
struct ACL;
typedef struct ACL ACL;
struct ACL_Tuple;
typedef struct ACL_Tuple ACL_Tuple;
struct acpi;
typedef struct acpi acpi;
struct active;
typedef struct active active;
struct Alarm;
typedef struct Alarm Alarm;
struct apic;
typedef struct apic apic;
struct arch;
typedef struct arch arch;
struct argument;
typedef struct argument argument;
struct arphdr;
typedef struct arphdr arphdr;
struct asl;
typedef struct asl asl;
struct AudioBuf;
typedef struct AudioBuf AudioBuf;
struct Auth;
typedef struct Auth Auth;
struct Auth_Tuple;
typedef struct Auth_Tuple Auth_Tuple;
struct callback;
typedef struct callback callback;
struct callback_register;
typedef struct callback_register callback_register;
struct CheckMap;
typedef struct CheckMap CheckMap;
struct chunk;
typedef struct chunk chunk;
struct command;
typedef struct command command;
struct completion;
typedef struct completion completion;
struct CPU;
typedef struct CPU CPU;
struct cpuinfo;
typedef struct cpuinfo cpuinfo;
struct CPU_KernelState;
typedef struct CPU_KernelState CPU_KernelState;
struct DDRM;
typedef struct DDRM DDRM;
struct DDRMRegion;
typedef struct DDRMRegion DDRMRegion;
struct DDRMSpec;
typedef struct DDRMSpec DDRMSpec;
struct DDRMTask;
typedef struct DDRMTask DDRMTask;
struct DDRMThreadState;
typedef struct DDRMThreadState DDRMThreadState;
struct desc;
typedef struct desc desc;
struct device;
typedef struct device device;
struct device_audio_ops;
typedef struct device_audio_ops device_audio_ops;
struct device_keyboard_ops;
typedef struct device_keyboard_ops device_keyboard_ops;
struct device_mouse_ops;
typedef struct device_mouse_ops device_mouse_ops;
struct device_tpm_ops;
typedef struct device_tpm_ops device_tpm_ops;
struct device_video_ops;
typedef struct device_video_ops device_video_ops;
struct dmi;
typedef struct dmi dmi;
struct dom;
typedef struct dom dom;
struct domain;
typedef struct domain domain;
struct e1000_context_desc;
typedef struct e1000_context_desc e1000_context_desc;
struct e1000_data_desc;
typedef struct e1000_data_desc e1000_data_desc;
struct e1000_eeprom_info;
typedef struct e1000_eeprom_info e1000_eeprom_info;
struct e1000_fflt_entry;
typedef struct e1000_fflt_entry e1000_fflt_entry;
struct e1000_ffmt_entry;
typedef struct e1000_ffmt_entry e1000_ffmt_entry;
struct e1000_ffvt_entry;
typedef struct e1000_ffvt_entry e1000_ffvt_entry;
struct e1000_hw;
typedef struct e1000_hw e1000_hw;
struct e1000_hw_stats;
typedef struct e1000_hw_stats e1000_hw_stats;
struct e1000_ipv4_at_entry;
typedef struct e1000_ipv4_at_entry e1000_ipv4_at_entry;
struct e1000_ipv6_at_entry;
typedef struct e1000_ipv6_at_entry e1000_ipv6_at_entry;
struct e1000_phy_info;
typedef struct e1000_phy_info e1000_phy_info;
struct e1000_phy_stats;
typedef struct e1000_phy_stats e1000_phy_stats;
struct e1000_rar;
typedef struct e1000_rar e1000_rar;
struct e1000_rx_desc;
typedef struct e1000_rx_desc e1000_rx_desc;
struct e1000_tx_desc;
typedef struct e1000_tx_desc e1000_tx_desc;
struct elf;
typedef struct elf elf;
struct elfhdr;
typedef struct elfhdr elfhdr;
struct ethhdr;
typedef struct ethhdr ethhdr;
struct EventChannelData;
typedef struct EventChannelData EventChannelData;
struct EventChannelState;
typedef struct EventChannelState EventChannelState;
struct evtchn;
typedef struct evtchn evtchn;
struct exec;
typedef struct exec exec;
struct facs;
typedef struct facs facs;
struct fadt;
typedef struct fadt fadt;
struct file;
typedef struct file file;
struct function;
typedef struct function function;
struct FXState;
typedef struct FXState FXState;
struct FXState_Flags;
typedef struct FXState_Flags FXState_Flags;
struct gdb;
typedef struct gdb gdb;
struct grant;
typedef struct grant grant;
struct hpet;
typedef struct hpet hpet;
struct hw;
typedef struct hw hw;
struct i;
typedef struct i i;
struct icmphdr;
typedef struct icmphdr icmphdr;
struct igmphdr;
typedef struct igmphdr igmphdr;
struct info;
typedef struct info info;
struct init;
typedef struct init init;
struct InitRD;
typedef struct InitRD InitRD;
struct InitRD_File;
typedef struct InitRD_File InitRD_File;
struct inode;
typedef struct inode inode;
struct iNode;
typedef struct iNode iNode;
struct intel;
typedef struct intel intel;
struct io;
typedef struct io io;
struct IO;
typedef struct IO IO;
struct iovec;
typedef struct iovec iovec;
struct IPC_Connection;
typedef struct IPC_Connection IPC_Connection;
struct IPC_DispatchArgs;
typedef struct IPC_DispatchArgs IPC_DispatchArgs;
struct iphdr;
typedef struct iphdr iphdr;
struct ipv;
typedef struct ipv ipv;
struct ipxhdr;
typedef struct ipxhdr ipxhdr;
struct irq;
typedef struct irq irq;
struct irqaction;
typedef struct irqaction irqaction;
struct IRQEventQueue;
typedef struct IRQEventQueue IRQEventQueue;
struct KBD;
typedef struct KBD KBD;
struct KBD_Data;
typedef struct KBD_Data KBD_Data;
struct kbd_drv_context;
typedef struct kbd_drv_context kbd_drv_context;
struct kernel;
typedef struct kernel kernel;
struct KernelThreadState;
typedef struct KernelThreadState KernelThreadState;
struct KSymbol;
typedef struct KSymbol KSymbol;
struct local;
typedef struct local local;
struct mc;
typedef struct mc mc;
struct MemStats;
typedef struct MemStats MemStats;
struct meshes;
typedef struct meshes meshes;
struct microcode;
typedef struct microcode microcode;
struct mm;
typedef struct mm mm;
struct modify;
typedef struct modify modify;
struct mp;
typedef struct mp mp;
struct mpc;
typedef struct mpc mpc;
struct multicall;
typedef struct multicall multicall;
struct N;
typedef struct N N;
struct N509;
typedef struct N509 N509;
struct net;
typedef struct net net;
struct net_device;
typedef struct net_device net_device;
struct net_udevice;
typedef struct net_udevice net_udevice;
struct NexusDevice;
typedef struct NexusDevice NexusDevice;
struct NexusLog;
typedef struct NexusLog NexusLog;
struct NexusOpenDevice;
typedef struct NexusOpenDevice NexusOpenDevice;
struct nf;
typedef struct nf nf;
struct notifier;
typedef struct notifier notifier;
struct or;
typedef struct or or;
struct page;
typedef struct page page;
struct Page;
typedef struct Page Page;
struct pbus;
typedef struct pbus pbus;
struct pci;
typedef struct pci pci;
struct pci_dev;
typedef struct pci_dev pci_dev;
struct PCIDev;
typedef struct PCIDev PCIDev;
struct pci_device_id;
typedef struct pci_device_id pci_device_id;
struct perfcounter;
typedef struct perfcounter perfcounter;
struct PktBootp;
typedef struct PktBootp PktBootp;
struct PktEther;
typedef struct PktEther PktEther;
struct PktIp;
typedef struct PktIp PktIp;
struct PktTftp;
typedef struct PktTftp PktTftp;
struct PktUdp;
typedef struct PktUdp PktUdp;
struct pm;
typedef struct pm pm;
struct poll;
typedef struct poll poll;
struct Port;
typedef struct Port Port;
struct proc;
typedef struct proc proc;
struct processor;
typedef struct processor processor;
struct ProfileEntry;
typedef struct ProfileEntry ProfileEntry;
struct pt;
typedef struct pt pt;
struct rangeset;
typedef struct rangeset rangeset;
struct RegressionTestControl;
typedef struct RegressionTestControl RegressionTestControl;
struct Regs;
typedef struct Regs Regs;
struct revectored;
typedef struct revectored revectored;
struct rsdp;
typedef struct rsdp rsdp;
struct rsdt;
typedef struct rsdt rsdt;
struct scatterlist;
typedef struct scatterlist scatterlist;
struct scheduler;
typedef struct scheduler scheduler;
struct screen;
typedef struct screen screen;
struct ScreenBuf;
typedef struct ScreenBuf ScreenBuf;
struct Sema;
typedef struct Sema Sema;
struct semaphore;
typedef struct semaphore semaphore;
struct serial;
typedef struct serial serial;
struct Service;
typedef struct Service Service;
struct ServiceReq;
typedef struct ServiceReq ServiceReq;
struct sha;
typedef struct sha sha;
struct sha1_ctx;
typedef struct sha1_ctx sha1_ctx;
struct skb;
typedef struct skb skb;
struct smart;
typedef struct smart smart;
struct sock;
typedef struct sock sock;
struct socket;
typedef struct socket socket;
struct soft;
typedef struct soft soft;
struct spxhdr;
typedef struct spxhdr spxhdr;
struct SymTable;
typedef struct SymTable SymTable;
struct sysinfo;
typedef struct sysinfo sysinfo;
struct task;
typedef struct task task;
struct tcphdr;
typedef struct tcphdr tcphdr;
struct this;
typedef struct this this;
struct thread;
typedef struct thread thread;
struct ThreadIPC;
typedef struct ThreadIPC ThreadIPC;
struct timer;
typedef struct timer timer;
struct timeval;
typedef struct timeval timeval;
struct TPMPCRComposite;
typedef struct TPMPCRComposite TPMPCRComposite;
struct TPMPCRInfo;
typedef struct TPMPCRInfo TPMPCRInfo;
struct TPMPCRSelection;
typedef struct TPMPCRSelection TPMPCRSelection;
struct TPMQuoteInfo;
typedef struct TPMQuoteInfo TPMQuoteInfo;
struct tss;
typedef struct tss tss;
struct uart;
typedef struct uart uart;
struct udevice;
typedef struct udevice udevice;
struct udphdr;
typedef struct udphdr udphdr;
struct user;
typedef struct user user;
struct UserThreadState;
typedef struct UserThreadState UserThreadState;
struct ustat;
typedef struct ustat ustat;
struct vcpu;
typedef struct vcpu vcpu;
struct vm;
typedef struct vm vm;
struct within;
typedef struct within within;
struct xen;
typedef struct xen xen;
struct xenctl;
typedef struct xenctl xenctl;
struct xenoprof;
typedef struct xenoprof xenoprof;
struct Xgt;
typedef struct Xgt Xgt;
struct xsdt;
typedef struct xsdt xsdt;


#endif
