/** NexusOS: IPC interface for kernel resources that corresponds to the 
  	     user interface generated by IPC.sc 			*/

#ifndef _USER_COMPAT_H_
#define _USER_COMPAT_H_

#include <nexus/ipc.h>

#define V_nexus(S) V(S)

#define SHA_CTX struct sha1_ctx
#define SHA1_Init(x)       sha1_init(x)
#define SHA1_Update(x,d,l) sha1_update(x,d,l)
#define SHA1_Final(o,x)    sha1_final(x,o)

#define Crypto_GetRandBytes(d,n) RAND_bytes(d,n)

enum ChannelOption;

int IPC_register(void);
int IPC_unregister(int oid);

// The definitions below are kept in-sync with IPC.sc

int IPC_CreatePort(int request);
int IPC_DestroyPort(int port);
int IPC_Send(int port_num, void *data, int dlen);
int IPC_Recv(int port_num, void *buf, int blen);
int ipc_sendpage(int port, void *data);
int ipc_recvpage(int port, void **data);

// XXX In the kernel, first argument of IPC_RecvCall() is interpreted as a BasicThread *
struct CallDescriptor;
Call_Handle IPC_RecvCall(Port_Handle _target_thread, char * message_dest, int * message_len_p, struct CallDescriptor * cdesc);

#include <nexus/ipc.h>
#include <nexus/ipd.h>
#include <nexus/ipc_private.h>
#include <nexus/thread.h>
#include <nexus/thread-inline.h>
#include <nexus/thread-private.h>

/* see declaration in kernel/nexus/ipc.c for explanation of changes */
int IPC_CallReturn(Call_Handle call_handle);
int IPC_TransferTo(Call_Handle call_handle, int desc_num, void * local, 
		   unsigned long off, int len);
int IPC_TransferFrom(Call_Handle call_handle, int desc_num, void * local, 
		     unsigned long off, int len);

typedef void (*IPC_CallHandler)(Call_Handle caller);
typedef int (*IPC_Bind_Handler)(Connection_Handle caller, Port_Handle *notification_port_handle);
typedef void (*IPC_Async_Handler)(IPD_ID source_ipd, Call_Handle call_handle, void *_ctx);

int IPC_AsyncSend(Connection_Handle conn_handle, 
		  void *message, int message_len,
		  struct TransferDesc *descs,
		  int num_transfer_descs);

int IPC_Caller(void);


#endif // _USER_COMPAT_H_

