#!/usr/bin/perl -w

use strict;

my $NQ_REQUEST_MASK_DIRECTION = (0x01);
my $NQ_REQUEST_REQUEST        = (0x00);
my $NQ_REQUEST_RESPONSE       = (0x01);

my $NQ_REQUEST_MASK_CLASS     = (0xF0);
my $NQ_REQUEST_INTERNAL       = (0x00);
my $NQ_REQUEST_ATTRIBUTE      = (0x10);
my $NQ_REQUEST_TRANSACTION    = (0x20);
my $NQ_REQUEST_TUPLE          = (0x30);
my $NQ_REQUEST_TRIGGER        = (0x40);

my $NQ_REQUEST_MASK_REQUEST           = (0x0F01);
my $NQ_REQUEST_INTERNAL_HELLO         = ($NQ_REQUEST_INTERNAL|0x000);
my $NQ_REQUEST_ATTRIBUTE_OP           = ($NQ_REQUEST_ATTRIBUTE|0x100);
my $NQ_REQUEST_TUPLE_CREATE           = ($NQ_REQUEST_TUPLE|0x100);
my $NQ_REQUEST_TUPLE_DELETE           = ($NQ_REQUEST_TUPLE|0x200);
my $NQ_REQUEST_TUPLE_ADD_ATT          = ($NQ_REQUEST_TUPLE|0x300);
my $NQ_REQUEST_TUPLE_DEL_ATT          = ($NQ_REQUEST_TUPLE|0x400);
my $NQ_REQUEST_TRANSACTION_START      = ($NQ_REQUEST_TRANSACTION|0x100);
my $NQ_REQUEST_TRANSACTION_COMMIT     = ($NQ_REQUEST_TRANSACTION|0x200);
my $NQ_REQUEST_TRANSACTION_ABORT      = ($NQ_REQUEST_TRANSACTION|0x300);
my $NQ_REQUEST_TRANSACTION_TEST       = ($NQ_REQUEST_TRANSACTION|0x400);
my $NQ_REQUEST_TRANSACTION_R_TEST     = ($NQ_REQUEST_TRANSACTION|0x500);
my $NQ_REQUEST_TRANSACTION_R_COMMIT   = ($NQ_REQUEST_TRANSACTION|0x600);
my $NQ_REQUEST_TRANSACTION_R_ABORT    = ($NQ_REQUEST_TRANSACTION|0x700);
my $NQ_REQUEST_TRANSACTION_R_REGISTER = ($NQ_REQUEST_TRANSACTION|0x800);
my $NQ_REQUEST_TRANSACTION_R_TESTRESP = ($NQ_REQUEST_TRANSACTION|0x900);
my $NQ_REQUEST_TRIGGER_CREATE         = ($NQ_REQUEST_TRIGGER|0x000);
my $NQ_REQUEST_TRIGGER_DELETE         = ($NQ_REQUEST_TRIGGER|0x100);
my $NQ_REQUEST_TRIGGER_FIRE           = ($NQ_REQUEST_TRIGGER|0x200);

my %map = (
NQ_REQUEST_MASK_DIRECTION=>$NQ_REQUEST_MASK_DIRECTION,
NQ_REQUEST_REQUEST       =>$NQ_REQUEST_REQUEST       ,
NQ_REQUEST_RESPONSE      =>$NQ_REQUEST_RESPONSE      ,

NQ_REQUEST_MASK_CLASS    =>$NQ_REQUEST_MASK_CLASS    ,
NQ_REQUEST_INTERNAL      =>$NQ_REQUEST_INTERNAL      ,
NQ_REQUEST_ATTRIBUTE     =>$NQ_REQUEST_ATTRIBUTE     ,
NQ_REQUEST_TRANSACTION   =>$NQ_REQUEST_TRANSACTION   ,
NQ_REQUEST_TUPLE         =>$NQ_REQUEST_TUPLE         ,
NQ_REQUEST_TRIGGER       =>$NQ_REQUEST_TRIGGER       ,

NQ_REQUEST_MASK_REQUEST          =>$NQ_REQUEST_MASK_REQUEST          ,
NQ_REQUEST_INTERNAL_HELLO        =>$NQ_REQUEST_INTERNAL_HELLO        ,
NQ_REQUEST_ATTRIBUTE_OP          =>$NQ_REQUEST_ATTRIBUTE_OP          ,
NQ_REQUEST_TUPLE_CREATE          =>$NQ_REQUEST_TUPLE_CREATE          ,
NQ_REQUEST_TUPLE_DELETE          =>$NQ_REQUEST_TUPLE_DELETE          ,
NQ_REQUEST_TUPLE_ADD_ATT         =>$NQ_REQUEST_TUPLE_ADD_ATT         ,
NQ_REQUEST_TUPLE_DEL_ATT         =>$NQ_REQUEST_TUPLE_DEL_ATT         ,
NQ_REQUEST_TRANSACTION_START     =>$NQ_REQUEST_TRANSACTION_START     ,
NQ_REQUEST_TRANSACTION_COMMIT    =>$NQ_REQUEST_TRANSACTION_COMMIT    ,
NQ_REQUEST_TRANSACTION_ABORT     =>$NQ_REQUEST_TRANSACTION_ABORT     ,
NQ_REQUEST_TRANSACTION_TEST      =>$NQ_REQUEST_TRANSACTION_TEST      ,
NQ_REQUEST_TRANSACTION_R_TEST    =>$NQ_REQUEST_TRANSACTION_R_TEST    ,
NQ_REQUEST_TRANSACTION_R_COMMIT  =>$NQ_REQUEST_TRANSACTION_R_COMMIT  ,
NQ_REQUEST_TRANSACTION_R_ABORT   =>$NQ_REQUEST_TRANSACTION_R_ABORT   ,
NQ_REQUEST_TRANSACTION_R_REGISTER=>$NQ_REQUEST_TRANSACTION_R_REGISTER,
NQ_REQUEST_TRANSACTION_R_TESTRESP=>$NQ_REQUEST_TRANSACTION_R_TESTRESP,
NQ_REQUEST_TRIGGER_CREATE        =>$NQ_REQUEST_TRIGGER_CREATE        ,
NQ_REQUEST_TRIGGER_DELETE        =>$NQ_REQUEST_TRIGGER_DELETE        ,
NQ_REQUEST_TRIGGER_FIRE          =>$NQ_REQUEST_TRIGGER_FIRE          ,
);

my %inv_map;

for my $k (keys %map) {
  $inv_map{$map{$k}} = $k;
}

while(my $line = <>) {
  if($line =~ /type=(\d+)/) {
    my $type = $1;
    my $dir = ($type & $NQ_REQUEST_MASK_DIRECTION);
    $type &= ~$NQ_REQUEST_MASK_DIRECTION;
    if(defined($inv_map{$type})) {
      my $replacement = "$inv_map{$type}" . ($dir ? "(response)" : "(req)");
      $line =~ s/type=(\d+)/type=$replacement/;
    }
  }
  print $line;
}
