/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H

enum arch_invocation_label {
    IA32PageDirectoryMap = nInvocationLabels + 0,
    IA32PageDirectoryUnmap = nInvocationLabels + 1,
    IA32PageTableMap = nInvocationLabels + 2,
    IA32PageTableUnmap = nInvocationLabels + 3,
    IA32IOPageTableMap = nInvocationLabels + 4,
    IA32PageMap = nInvocationLabels + 5,
    IA32PageRemap = nInvocationLabels + 6,
    IA32PageUnmap = nInvocationLabels + 7,
    IA32PageMapIO = nInvocationLabels + 8,
    IA32PageGetAddress = nInvocationLabels + 9,
    IA32ASIDControlMakePool = nInvocationLabels + 10,
    IA32ASIDPoolAssign = nInvocationLabels + 11,
    IA32IOPortIn8 = nInvocationLabels + 12,
    IA32IOPortIn16 = nInvocationLabels + 13,
    IA32IOPortIn32 = nInvocationLabels + 14,
    IA32IOPortOut8 = nInvocationLabels + 15,
    IA32IOPortOut16 = nInvocationLabels + 16,
    IA32IOPortOut32 = nInvocationLabels + 17,
    IA32IOSpaceRemovePassthrough = nInvocationLabels + 18,
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
